### PR TITLE
Consolidates tests and using pytest marking

### LINKED ISSUE #147: S3 [Task] Add stand-alone docker unit test runner
Task | Add stand-alone docker unit test runner
----------|----------
Task Title | Add stand-alone docker unit test runner
User Story | #106 
Epic | 
T-shirt size default is S(mall) | S
Story Points - Fibonacci (1,2,3,5) | 1
Description | Create a docker script for running unit tests
Business Need (the why): | Tests require dependencies that may not be installed. Allow running of unit tests with a docker container with installed dependencies.
Applications or Systems impacted | 
Dependencies | 
Assumptions |

### PR DESCRIPTION
**Pull request by adamgering**
Consolidates test in the /tests directory.
Sets up tests to be run via ```pytest```
Adds pytest marking annotations (e.g. ```@pytest.mark.unit```)
so you can pick which tests to run.
```pytest -m "unit"``` for unit tests
```pytest -m "integration"``` for integration tests
Tests may be run and re-run interactively via shell.
```docker exec -it rbac-shell bash```
```pytest```
Or one-off via a clean docker image:
```bin/build -t```

Resolves #147, addresses #106 and #143

### CODE REVIEW

**Comment by adamgering** [comment]
Note, when run interactively, there is one integration test will presently fail on subsequent runs as it is counting the number of items in the blockchain. That test should be revised so that doesn't happen.

**Comment by adamgering** [comment]
Presently there is an excessive amount of console logging when tests run. This will need to be investigated. I believe we may need to upgrade to later versions of sawtooth (1.05 from 1.0) to eliminate some of these.

**Comment by adamgering** [comment]
Resolves issue #147

**Comment by adamgering** [comment]
Partially resolves issue #143

**Comment by adamgering** [comment]
Addresses issue #106

**Comment by adamgering** [comment]
Travis check failure is due to wrong configuration of the Travis environment. #176 A pull request fixing the Travis environment such that this PR passes checks is a dependency.

**Comment by boydjohnson** [comment]
@adamgering It would be nice if this was broken up into more commits. There are the new Unit tests, which could be their own commit, and then adding PyTest markings, which could be its own commit.

**Comment by adamgering** [comment]
> @adamgering It would be nice if this was broken up into more commits. There are the new Unit tests, which could be their own commit, and then adding PyTest markings, which could be its own commit.

You're right, we're trying to keep commits and PRs as small limited in scope as possible.

Would one PR with 3 commits (the move, the new tests, the markings) work best for that? I didn't think 3 PRs would make sense given the cadence of approvals and cross-dependencies. As a policy we're trying to make all PRs only 1 commit, but perhaps that's not the correct approach if the commit separation makes sense.

**Comment by boydjohnson** [comment]
Yeah, 1 PR with 3 commits makes the most sense to me.

**Comment by adamgering** [comment]
Pending commit split and rebase

**Comment by adamgering** [comment]
Rebased, conflicts resolved and split into separate commits. 
Ready for review and and approval+rebase&merge.

**Pull request merged**
