### PR TITLE
Proposing adding Adam G. as maintainer

### PR DESCRIPTION
**Pull request by mtn217**
Discussions were had, and it was agreed upon to have Adam join as
a maintainer in lieu of Zac Delventhal.

Signed-off-by: Michael Nguyen <michael.nguyen79@t-mobile.com>

### CODE REVIEW

**Comment by chrisspanton** [comment]
This is great! Thanks everyone for helping ensure we have a healthy project here.

**Comment by mtn217** [comment]
Zac Delventhal has been added back to the Maintainers list.

**Comment by vaporos** [comment]
Removing a maintainer is generally done only after a year or more of inactivity or at the request of that maintainer. (Special cases too, I suppose.) We actually want maintainers to stick with the projects as long as they are willing to do so, ideally. Unless Zac specifically requested to be removed, I do not think it is appropriate to remove him.

There was perhaps a misunderstanding that we should keep the maintainers list fixed at six, but that is not necessary.  We created the original list with the "top five" rule, but there is no need to restrict that count moving forward. On other components, the number of maintainers varies from 5 (just enough to function) to 14 (core, large number of long-term contributors).

Important criteria for adding a maintainer is history with the project and a good working relationship with the other maintainers.  The governance RFC has some more text about general criteria that existing maintainers should consider when adding a new maintainer.  On purpose, those are guidelines only, and the judgement is left to the maintainers.

**Comment by adamgering** [comment]
Suggest @mtn217 modify this PR to only add me and leave Zac. Seven is a lucky number.

**Comment by mtn217** [comment]
@adamgering - I can modify the PR, however @chrisspanton mentioned in rocket chat today that Zac would not be actively engaged in this project and he said he was fine with being removed from the Maintainers list.

**Comment by mtn217** [comment]
@kthblmfld - Zac has been added back to the Maintainers list as requested.

**Comment by kthblmfld** [comment]
I would like to be on this list as I have been active in ensuring changes go in and that quality is moving upwards, and since @vaporos indicated there is no hard rule limiting maintainers to 5. Otherwise, this will become an impediment to any commitments I have on the delivery timeline. 

I am happy to add myself in a separate PR if necessary. @chrisspanton @vaporos looking to you folks for proper next steps regarding this PR going in and my proposed change. Thanks

**Pull request merged**
