### PR TITLE
Add requirements.txt to manage python container dependencies

### PR DESCRIPTION
**Pull request by jbobo**
Fix Issue #171 - Added requirements.txt to each python container directory to manage dependencies and edited Dockerfiles to use requirements.txt where appropriate.

### CODE REVIEW

**Comment by jbobo** [comment]
@adamgering I addressed the review and removed the redundant imports. Added description to the commit message after rebasing.

**Comment by adamgering** [comment]
Docker images are rebuilt if the Dockerfile changes. They are not if requirements.txt changes. Thus, moving requirements to requirements.txt is likely counter-productive.

**Comment by adamgering** [comment]
Why are new dependencies being installed via pip (through requirements.txt) that were not previous installed via pip?

**Comment by adamgering** [comment]
I'm going to close this PR, the change is not required.

**Comment by jbobo** [comment]
@adamgering this change was already approved in our sprint planning. The change to using requirements.txt allows dependencies to be added or removed without editing the Dockerfiles. This also aligns with the intended use of requirements.txt which is to configure deployment environments.

**Pull request closed without merging**
