### PR TITLE
Add Travis marker file & Travis/Apache 2.0 license badges

### PR DESCRIPTION
**Pull request by devsatishm**
Benefits - 

- Once enabled, Travis kicks off CI process for each PR, marks it merge-ready if checks configured in `.travis.yml` file are successful. 
- Repo will now have badges for Travis & Apache 2.0 license

### CODE REVIEW

**Comment by adamgering** [comment]
Can you try squashing this pull request?

https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by devsatishm** [comment]
@adamgering  Done.

**Comment by adamgering** [comment]
Can you also rebase the commit.

**Comment by devsatishm** [comment]
Yes, done.

**Pull request merged**
