### PR TITLE
[HOTFIX] (Re)build by default in start script

### PR DESCRIPTION
**Pull request by jbobo**
Setting ./bin/start to rebuild by default. Hotfix for Issue #291.

[Issue: #291]

Signed-off-by: jbobo <j.ned@bobonana.me>

### CODE REVIEW

**Comment by jbobo** [comment]
@adamgering So what should we do? We've confirmed that our documented start method, running `./bin/start` produces errors.

**Comment by kthblmfld** [comment]
@adamgering It looks like the problem remains where deploying the project in non-dev mode results in errors accessing the compiled protobuf files. 

Regarding your comment/request for changes: Please recommend an alternative solution to the problem if you have one.

**Comment by adamgering** [comment]
Let's remove non-dev mode then, it's a feature built for nobody, no one uses it and no one is blocked.

**Comment by adamgering** [comment]
It can be addressed in a PR to cleanup the DockerFiles. Until then, it's low priority.

**Comment by kthblmfld** [comment]
This is only low-priority to those who are up to speed on whatever undocumented process builds without error. The build takes a long time to carry out, and if the documentation leads people to follow these steps then more time is wasted in reattempts and escalation than it would be with the additional build step. 

This issue has already left a number of contributors blocked trying to figure out what they did wrong. It needs to be addressed even if the fix is sub-optimal.

**Comment by jbobo** [comment]
I agree that this is sub-optimal, but it's a valid issue that @nadiabahrami brought up a couple days ago and has been dealing with. We know the issue involves containers finding the protobuf files but we don't have a permanent solution yet. Since we know running `-b` with the start script fixes the issue for now and causes no immediate harm, let's just push this as a hotfix to prevent impacting new contributors and leave Issue #291 open to be solved with a permanent fix when we have time.

**Comment by jbobo** [comment]
@adamgering if you can run `script` and show us that running in dev-mode without `-b` fixes the issue then I'm down to rebase my commit and go with that instead. At the moment tho we've got proof that this works and I'd like to merge it now to minimize the impact to new contributors.

**Comment by adamgering** [comment]
Replaced by PR #351

**Comment by kthblmfld** [comment]
Ok, will pull and test out PR #351 later. Thanks @jbobo, @adamgering, @nadiabahrami for sorting this out!

**Pull request closed without merging**
