### PR TITLE
[ISSUE #187 FIX] Initial Sphinx Installation

### PR DESCRIPTION
**Pull request by jbobo**
Initialize Sphinx with `sphinx-quickstart` in project directory.

[Issue: #187]

Signed-off-by: jbobo <j.ned@bobonana.me>

### CODE REVIEW

**Comment by mtn217** [comment]
Should we create a docs folder to place all of these files in? Similar to the sawtooth-core repo format?

**Comment by adamgering** [comment]
Yes, a docs folder.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jbobo** [comment]
commented in Issue #187 when I initialized sphinx to see if we should change any of the default settings. I can change the default docs folder to './docs' but would it be more appropriate to close PR #201 and open a new one? sphinx uses `_static` for static doc pages `_templates` for templates and `_build` for the transpiled html pages. I know `docs` is a standard way to store docs, but I also think we shouldn't stray too far from the Sphinx defaults. Would it be acceptable to use the default directories within `./docs`, for `./docs/_static`, `./docs/_templates`, and `./docs/_build`? 

@mtn217 @adamgering

**Comment by adamgering** [comment]
Sure, let's get started and go from there. Defaults are fine.

**Pull request merged**
